[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
yellow = "#fce94f"

[colors.normal]
black = "#3e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#1a1a1a"
foreground = "#eeeeec"

[font]
size = 7

[font.normal]
family = "MesloLGS NF"

[selection]
save_to_clipboard = true

[window]
opacity = 0.9
